<script src="https://cdn.jsdelivr.net/npm/sweetalert2@8"></script>
<?php 
require_once( str_replace('//','/',dirname(__FILE__).'/') .'../../../../wp-config.php');

// echo "<pre>";
// print_r($_POST);
// echo "file";
 //print_r($_FILES);


 //exit();
if ( isset($_POST) && !empty($_POST) )
{
    if ( ! function_exists( 'wp_handle_upload' ) ) {
            require_once( ABSPATH . 'wp-admin/includes/file.php' );
        }

        $uploadedfile = $_FILES['file'];

        $upload_overrides = array( 'test_form' => false );

        $movefile = wp_handle_upload( $uploadedfile, $upload_overrides );

        if ( $movefile && ! isset( $movefile['error'] ) ) {
            echo "File is valid, and was successfully uploaded.\n";
            //print_r( $movefile );
        } else {
            /**
             * Error generated by _wp_handle_upload()
             * @see _wp_handle_upload() in wp-admin/includes/file.php
             */
            echo $movefile['error'];
        }

    $name = $_POST['name'];
    $school_Address = $_POST['school_Address'];
    $country_code = $_POST['country_code'];
    $type_of_school = $_POST['type_of_school'];
    $image_url = $movefile['url'];

    global $wpdb;
    $table_name      = $wpdb->prefix . "schools";
    //print_r($wpdb->insert($tablename, $data)); exit();
    $res = $wpdb->query("INSERT INTO ".$table_name."(`school_name`, `school_Address`, `country_code`, `type_of_school`,`school_image`) VALUES (
        '".$name."',
        '".$school_Address."',
        '".$country_code."',
        '".$type_of_school."',
        '".$image_url."')");


    // print_r($wpdb); 
    // exit();
if ($res == TRUE) {

   ?> 
   <script>
let timerInterval
Swal.fire({
  title: 'Schule eintragen',
  text: "Kurz warten..",
  type: 'success',
  timer: 1500,
  onBeforeOpen: () => {
    Swal.showLoading()
    timerInterval = setInterval(() => {
      Swal.getContent().querySelector('strong')
        .textContent = Swal.getTimerLeft()
    }, 100)
  },
  onClose: () => {
    clearInterval(timerInterval)
  }
}).then((result) => {
  if (
    /* Read more about handling dismissals below */
    result.dismiss === Swal.DismissReason.timer
  ) {
    window.location.href = '<?=admin_url()."admin.php?page=Add-new"?>'; //will redirect to add school page
    console.log('I was closed by the timer')
  }
})
</script>

 <?php
}
else
{  ?> 
	<script>
    Swal.fire({
  type: 'error',
  title: 'Ups...',
  text: 'Da ist etwas schiefgelaufen!'
})
		</script>
		
		<?php
}


    }
?>